services:
  db:
    container_name: postgresql_db_analytics
    image: postgres:17
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/docker-entrypoint-initdb.d/data:ro

  pgadmin:
    container_name: pgadmin_analytics
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      # This line below helps bypass some permission checks in certain environments
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      # Use the named volume for everything internal to pgAdmin
      - pgadmin_internal_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgadmin_internal_data: